# -*- coding: utf-8 -*-
"""GRAFICALinealCongruenteConM2e48 punto 2_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bCBxKPn4ZptJQJTnjWUFCVBD8InQIaPR
"""

import matplotlib.pyplot as plt
import numpy as np


datalc2e48 = np.loadtxt('puntosLC_2e48.txt')

x = datalc2e48[:,0]
y = datalc2e48[:,1]

# Graficar
plt.plot(x, y, marker='+', linestyle = "", color = "b")
plt.xlabel('$x_{i}$')
plt.ylabel('$x_{i+1}$')
plt.grid(True)
plt.title('Método lineal congruente con $M=2^{48}$')
plt.show()