# -*- coding: utf-8 -*-
"""lineal congruente vs. Twister

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aW7oMO9jzDmB0sdcBoNpEEL8JDQu9QsF
"""

import matplotlib.pyplot as plt
import numpy as np


datalc = np.loadtxt('puntoslc.txt')

x = datalc[:,0]
y = datalc[:,1]

# Graficar
plt.plot(x, y, marker='+', linestyle = "", color = "b")
plt.xlabel('$x_{i}$')
plt.ylabel('$x_{i+1}$')
plt.grid(True)
plt.title('Método lineal congruente')
plt.show()

datatwi = np.loadtxt('puntostwi.txt')

x = datatwi[:,0]
y = datatwi[:,1]

# Graficar
plt.plot(x, y, marker='+', linestyle = "", color = "b")
plt.xlabel('$x_{i}$')
plt.ylabel('$x_{i+1}$')
plt.grid(True)
plt.title('Método Mersenne Twister')
plt.show()