# -*- coding: utf-8 -*-
"""Regla 30 y mapeo logístico

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11lKsOJlA3IDXIZ8X5cxFZiiXAGVj5dzA
"""



"""# regla 30"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile regla_30.cpp
# #include <stdint.h>
# #include <iostream>
# 
# int main() {
#   uint64_t state =1u <<31;
#   std::cout<<state<<"\n";
#   for (int i =0; i <32; ++i){
#     for (int j =64; j--;){
#       std::cout<<char(state >> j & 1 ? 'O' : '.');
#     }
#     std::cout<<"  "<<state %10000<<'\n';
#     state = (state >>1) ^ (state | state <<1);
#   }
# }

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# g++ regla_30.cpp -o regla_30
# ./regla_30 > regla_30.txt

# Commented out IPython magic to ensure Python compatibility.
# #Extract numeric data from rule of 30 cm juas juas
# %%writefile regla_30_numeric.cpp
# #include <stdint.h>
# #include <iostream>
# #include <fstream>
# 
# int main() {
#   uint64_t state = 1u << 31;
#   // outputFile << state << "\n"; // Optionally print initial full state
# 
#   for (int i = 0; i < 32; ++i) {
#     std::cout << state % 10000 << '\n'; // Only print the numerical value for analysis
#     state = (state >> 1) ^ (state | state << 1);
#   }
# 
# }

"""### Compiling and Running the Numeric Rule 30 Generator"""

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# g++ regla_30_numeric.cpp -o regla_30_numeric
# ./regla_30_numeric > regla_30_numeric.txt

"""### Statistical Analysis of Rule 30 Numeric Output"""

import pandas as pd
import matplotlib.pyplot as plt

df_regla30 = pd.read_csv('regla_30_numeric.txt', header=None, names=['numeric_state'])

# Calculate statistics
mean_val = df_regla30['numeric_state'].mean()
variance_val = df_regla30['numeric_state'].var()
skewness_val = df_regla30['numeric_state'].skew()

print(f"Mean of numeric_state: {mean_val:.2f}")
print(f"Variance of numeric_state: {variance_val:.2f}")
print(f"Skewness of numeric_state: {skewness_val:.2f}")

plt.hist(df_regla30['numeric_state'], bins=10, align='left', rwidth=0.8, density=True)
plt.title('Histograma para los estados númericos de la Regla 30')
plt.xlabel('Valores(% 10000)')
plt.ylabel('Frequencia')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.savefig('hist_regla30.png')
plt.show()

"""# mapeo logistico"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile mapeo_logistico.cpp
# #include <iostream>
# #include <math.h>
# #include <list>
# using namespace std;
# int main(){
#   double x=0.1;
#   for (int n; n < 1000; n++){
#     cout << x << endl;
#     x = 4*x*(1-x);
#   }
# 
# }
#

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# g++ mapeo_logistico.cpp -o mapeo_logistico
# ./mapeo_logistico > mapeo_logistico.txt

df_logistico = pd.read_csv('mapeo_logistico.txt', header=None, names=['numeric_state'])

# Calculate statistics
mean_val = df_logistico['numeric_state'].mean()
variance_val = df_logistico['numeric_state'].var()
skewness_val = df_logistico['numeric_state'].skew()

print(f"Mean of numeric_state: {mean_val:.2f}")
print(f"Variance of numeric_state: {variance_val:.2f}")
print(f"Skewness of numeric_state: {skewness_val:.2f}")

plt.hist(df_logistico['numeric_state'], bins=10, align='left', rwidth=0.8, density=True)
plt.title('Histograma modelo logistico')
plt.xlabel('Valores')
plt.ylabel('Frequencia')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.savefig('hist_logistico.png')
plt.show()

